#!/bin/bash
wget https://mirrors.ustc.edu.cn/epel//epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
yum clean all
#yum -y update
yum -y install gcc g++ gcc+ gcc-c++
yum -y install git unzip zip nginx curl gd2 gd net-tools mariadb mariadb-server npm
yum -y install pcre-devel openssl openssl-devel
yum -y install libxml2 libxml2-devel libmcrypt libXpm-devel libc-client-devel libcurl-devel libjpeg-devel libpng-devel libicu-devel openldap-devel
yum -y install libevent-devel libxslt-devel freetype-devel unixODBC-devel aspell-devel readline-devel net-snmp-devel enchant-devel
yum -y install bzip2 bzip2-devel m2crypto libsodium
yum -y install gmp-devel readline-devel net-snmp-devel libxslt-devel
#wget https://github.com/WeakSelf/AutoInstall/raw/master/SSRPanelInstall && chmod +x SSRPanelInstall && ./SSRPanelInstall 
cd ~
wget https://github.com/WeakSelf/AutoInstall/raw/master/libmcrypt-2.5.7.zip
unzip libmcrypt-2.5.7.zip
cd ~/libmcrypt-2.5.7
make install

echo "install php7.1"
cd ~
wget https://github.com/WeakSelf/AutoInstall/raw/master/php.zip
wget https://github.com/WeakSelf/AutoInstall/raw/master/php.z01
zip php.zip -s=0 --out php-7.1.zip
unzip php-7.1.zip
cd ~/php-7.1.12
make install
export PATH=$PATH:/usr/local/php7/bin
cp ~/php-7.1.12/sapi/fpm/php-fpm.service /usr/lib/systemd/system/
chmod 754 /usr/lib/systemd/system/php-fpm.service
cp ~/php-7.1.12/php.ini-production /usr/local/php7/etc/php.ini
cp /usr/local/php7/etc/php-fpm.conf.default /usr/local/php7/etc/php-fpm.conf
systemctl enable php-fpm

cd /usr/local/php7/etc/php-fpm.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/www.conf

systemctl start nginx
cd /etc/nginx/
mv nginx.conf nginx.conf.origin
wget https://github.com/WeakSelf/AutoInstall/raw/master/nginx.conf

cd /etc/nginx/conf.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/ssrpanel.conf
systemctl enable nginx
nginx -s reload

groupadd www
useradd -g www www -s /sbin/nologin

echo "install mariadb"
systemctl start mariadb
rootpwd=`openssl rand -base64 10`
ssrpanelpwd=`openssl rand -base64 10`
echo $rootpwd
echo $ssrpanelpwd

echo -e "\n" "y\n" "123456\n" "123456\n" "y\n" "y\n" "y\n" "y\n" | mysql_secure_installation
mysqladmin -uroot -p123456 password $rootpwd
mysql -uroot --password=$rootpwd -e "CREATE DATABASE ssrpanel;"
mysql -uroot --password=$rootpwd -e "GRANT ALL ON ssrpanel.* TO 'ssrpanel' IDENTIFIED BY '$ssrpanelpwd';"
mysql -uroot --password=$rootpwd -e "FLUSH PRIVILEGES;"

systemctl enable mariadb
touch ~/pwd.txt
echo "mariadb root pwd : $rootpwd" >> ~/pwd.txt
echo "mariadb ssrpanel pwd : $ssrpanelpwd" >> ~/pwd.txt

echo "install ssrpanel"
cd /home/www
git clone https://github.com/ssrpanel/ssrpanel.git

sed -i "s/'username' => 'root',/'username' => 'ssrpanel',/" /home/www/ssrpanel/config/database.php
sed -i "s/'password' => '',/'password' => '$ssrpanelpwd',/" /home/www/ssrpanel/config/database.php
sed -i "s/'debug' => true,/'debug' => false,/" /home/www/ssrpanel/config/app.php
cd /home/www/ssrpanel
mysql -uroot --password=$rootpwd ssrpanel </home/www/ssrpanel/sql/db.sql
mysql -uroot --password=$rootpwd ssrpanel </home/www/ssrpanel/sql/update/20180119.sql
php composer.phar install
echo -e "yes" | php artisan key:generate
chown -R www:www .
chmod -R 777 storage/

echo "Asia/Shanghai" > /etc/sysconfig/clock
echo -e "\n" | cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
yum install ntp
echo "ntpdate cn.pool.ntp.org" >> /etc/rc.d/rc.local
chmod +x /etc/rc.d/rc.local
echo '* * * * * /usr/local/php7/bin/php /home/www/ssrpanel/artisan schedule:run >> /dev/null 2>&1' | crontab -e 
firewall-cmd --zone=public --add-port=80/tcp --permanent
echo "SSRPanel Complete!"

cd ~
wget -c https://github.com/ssrpanel/ssrpanel/raw/master/server/ssr-3.4.0.tar.gz 
tar -zxvf ssr-3.4.0.tar.gz 
cd shadowsocksr   
./setup_cymysql.sh
sed -i -e "s/server_host/127.0.0.1/g" usermysql.json
sed -i -e "s/server_port/3306/g" usermysql.json
sed -i -e "s/server_db/ssrpanel/g" usermysql.json
sed -i -e "s/server_user/ssrpanel/g" usermysql.json
sed -i -e "s/server_password/$ssrpanelpwd/g" usermysql.json
sed -i -e "s/nodeid/1/g" usermysql.json
sed -i -e "s/noderatio/1/g" usermysql.json
sed -i -e "s/\"fast_open\": false/\"fast_open\": true/g" user-config.json
sed -i -e "s/\"server_ipv6\": \"::\",//g" user-config.json
chmod +x *.sh
echo "/root/shadowsocksr/run.sh" >> /etc/rc.d/rc.local
firewall-cmd --zone=public --add-port=10000-40000/tcp --permanent
firewall-cmd --zone=public --add-port=10000-40000/udp --permanent


wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh
chmod +x bbr.sh
echo -e "\n" "yes\n" |  ./bbr.sh

reboot
