#!/bin/bash
yum -y install gcc g++ gcc+ gcc-c++
yum -y install git unzip zip nginx curl gd2 gd net-tools mariadb mariadb-server npm
yum -y install pcre-devel openssl openssl-devel
yum -y install libxml2 libxml2-devel libmcrypt libXpm-devel libc-client-devel libcurl-devel libjpeg-devel libpng-devel libicu-devel openldap-devel
yum -y install libevent-devel libxslt-devel freetype-devel unixODBC-devel aspell-devel readline-devel net-snmp-devel enchant-devel
yum -y install bzip2 bzip2-devel
yum -y install gmp-devel readline-devel net-snmp-devel libxslt-devel

echo "install php7.1"
cd ~

wget https://github.com/WeakSelf/AutoInstall/raw/master/php.zip
wget https://github.com/WeakSelf/AutoInstall/raw/master/php.z01
zip php.zip -s=0 --out php-7.1.zip
unzip php-7.1.zip
cd ~/php-7.1.12
make install
export PATH=$PATH:/usr/local/php7/bin
cp ~/php-7.1.12/sapi/fpm/php-fpm.service /usr/lib/systemd/system/
chmod 754 /usr/lib/systemd/system/php-fpm.service
cp ~/php-7.1.12/php.ini-production /usr/local/php7/etc/php.ini
systemctl enable php-fpm

cd ~
wget https://github.com/WeakSelf/AutoInstall/raw/master/libmcrypt-2.5.7.zip
unzip libmcrypt-2.5.7.zip
cd ~/libmcrypt-2.5.7
make install

cd /usr/local/php7/etc/php-fpm.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/www.conf


cd /etc/nginx/
mv nginx.conf nginx.conf.origin
wget https://github.com/WeakSelf/AutoInstall/raw/master/nginx.conf

cd /etc/nginx/conf.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/ssrpanel.conf
systemctl enable nginx

groupadd www
useradd -g www www -s /sbin/nologin


echo "install ssrpanel"
cd /home/www
git clone https://github.com/ssrpanel/ssrpanel.git
cd /home/www/ssrpanel
php composer.phar install
php artisan key:generate
chown -R www:www .
chmod -R 777 storage/


echo "install mariadb"
systemctl start mariadb
rootpwd=`openssl rand -base64 10`
ssrpanelpwd=`openssl rand -base64 10`
echo $rootpwd
echo $ssrpanelpwd

echo -e "\n" "y\n" '$rootpwd\n' '$rootpwd\n' 'y\n' 'y\n' 'y\n' 'y\n' | mysql_secure_installation
mysql -uroot -p$rootpwd -e "CREATE DATABASE ssrpanel;"
mysql -uroot -p$rootpwd -e "GRANT ALL ON ssrpanel.* TO 'ssrpanel' IDENTIFIED BY '$ssrpanelpwd';"
mysql -uroot -p$rootpwd -e "FLUSH PRIVILEGES;"
mysql -uroot -p$rootpwd ssrpanel < /home/www/ssrpanel/sql/db.sql
systemctl enable mariadb
touch ~/pwd.txt
echo "mariadb root pwd : $rootpwd" >> ~/pwd.txt
echo "mariadb ssrpanel pwd : $ssrpanelpwd" >> ~/pwd.txt
sed 's/"'username' => 'root',"/"'username' => 'ssrpanel',"/' /home/www/ssrpanel/config/database.php
sed 's/\'password\' => \'\',/\'password\' => \'$ssrpanelpwd\',/' /home/www/ssrpanel/config/database.php

#echo '* * * * * php /home/www/ssrpanel/artisan schedule:run >> /dev/null 2>&1' | crontab -e 
firewall-cmd --zone=public --add-port=80/tcp --permanent
echo "Complete!"
