#!/bin/bash
wget https://mirrors.ustc.edu.cn/epel//epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
yum clean all
#yum -y update
yum -y install gcc g++ gcc+ gcc-c++
yum -y install git unzip zip nginx curl gd2 gd net-tools mariadb mariadb-server npm
yum -y install pcre-devel openssl openssl-devel
yum -y install libxml2 libxml2-devel libmcrypt libXpm-devel libc-client-devel libcurl-devel libjpeg-devel libpng-devel libicu-devel openldap-devel
yum -y install libevent-devel libxslt-devel freetype-devel unixODBC-devel aspell-devel readline-devel net-snmp-devel enchant-devel
yum -y install bzip2 bzip2-devel
yum -y install gmp-devel readline-devel net-snmp-devel libxslt-devel

cd ~
wget https://github.com/WeakSelf/AutoInstall/raw/master/libmcrypt-2.5.7.zip
unzip libmcrypt-2.5.7.zip
cd ~/libmcrypt-2.5.7
make install

echo "install php7.1"
cd ~
wget https://github.com/WeakSelf/AutoInstall/raw/master/php.zip
wget https://github.com/WeakSelf/AutoInstall/raw/master/php.z01
zip php.zip -s=0 --out php-7.1.zip
unzip php-7.1.zip
cd ~/php-7.1.12
make install
export PATH=$PATH:/usr/local/php7/bin
cp ~/php-7.1.12/sapi/fpm/php-fpm.service /usr/lib/systemd/system/
chmod 754 /usr/lib/systemd/system/php-fpm.service
cp ~/php-7.1.12/php.ini-production /usr/local/php7/etc/php.ini
cp /usr/local/php7/etc/php-fpm.conf.default /usr/local/php7/etc/php-fpm.conf
systemctl enable php-fpm

cd /usr/local/php7/etc/php-fpm.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/www.conf

systemctl start nginx
cd /etc/nginx/
mv nginx.conf nginx.conf.origin
wget https://github.com/WeakSelf/AutoInstall/raw/master/nginx.conf

cd /etc/nginx/conf.d/
wget https://github.com/WeakSelf/AutoInstall/raw/master/ssrpanel.conf
systemctl enable nginx
nginx -s reload

groupadd www
useradd -g www www -s /sbin/nologin

echo "install mariadb"
systemctl start mariadb
rootpwd=`openssl rand -base64 10`
ssrpanelpwd=`openssl rand -base64 10`
echo $rootpwd
echo $ssrpanelpwd

echo -e "\n" "y\n" "123456\n" "123456\n" "y\n" "y\n" "y\n" "y\n" | mysql_secure_installation
mysqladmin -uroot -p123456 password $rootpwd
mysql -uroot --password=$rootpwd -e "CREATE DATABASE ssrpanel;"
mysql -uroot --password=$rootpwd -e "GRANT ALL ON ssrpanel.* TO 'ssrpanel' IDENTIFIED BY '$ssrpanelpwd';"
mysql -uroot --password=$rootpwd -e "FLUSH PRIVILEGES;"

systemctl enable mariadb
touch ~/pwd.txt
echo "mariadb root pwd : $rootpwd" >> ~/pwd.txt
echo "mariadb ssrpanel pwd : $ssrpanelpwd" >> ~/pwd.txt

echo "install ssrpanel"
cd /home/www
git clone https://github.com/ssrpanel/ssrpanel.git

sed "s/'username' => 'root',/'username' => 'ssrpanel',/" /home/www/ssrpanel/config/database.php >/home/www/ssrpanel/config/database.php
sed "s/'password' => '',/'password' => '$ssrpanelpwd',/" /home/www/ssrpanel/config/database.php >/home/www/ssrpanel/config/database.php

cd /home/www/ssrpanel
mysql -uroot --password=$rootpwd ssrpanel </home/www/ssrpanel/sql/db.sql
php composer.phar install
echo -e "yes" | php artisan key:generate
chown -R www:www .
chmod -R 777 storage/

#echo '* * * * * php /home/www/ssrpanel/artisan schedule:run >> /dev/null 2>&1' | crontab -e 
firewall-cmd --zone=public --add-port=80/tcp --permanent
echo "Complete!"
